spring:
    jackson:
        date-format: yyyy-MM-dd
        timezone: GMT+0
        serialization:
            write-dates-as-timestamps: false #时间戳设置true 覆盖date-format
    datasource:
            url: jdbc:postgresql://127.0.0.1:5432/tvseries?stringtype=unspecified&ApplicationName=tutorial
            username: panda
            password: panda

logging:
    level:
        ROOT: ERROR
    file:
        name: target.app.log

mybatis:
    configuration:
        map-underscore-to-camel-case: true